### ISSUE TITLE
Disable In Progress/Commenced message

### ISSUE THREAD

**Issue by petobens** [WhoIsSethDaniel/lualine-lsp-progress.nvim#6] opened 2023-01-23 22:21 UTC
@rorystephenson @WhoIsSethDaniel after https://github.com/WhoIsSethDaniel/lualine-lsp-progress.nvim/pull/4  I'm always seeing the In Progress/commenced message. I want lualine only to display when the lsp is loading. I tried removing the commenced bit from the following config but without success:
```lua
            {
                'lsp_progress',
                component_separator = { left = '', right = '' },
                message = {
                    initializing = 'Start…',
                    commenced = '*',
                    completed = 'Done!',
                },
                display_components = {
                    'lsp_client_name',
                    { 'message' },
                },
```

Any pointers are greatly appreciated.

Also is there a way to disable showing null-ls? Thanks in advance for the help!

**Comment by rorystephenson** [comment] 2023-01-24 09:02
Hmm it must be a difference in how the lsp clients work, it works fine for me in dart, sorry about that! What lsp client are you using so I can try to reproduce the issue?

**Comment by petobens** [comment] 2023-01-24 10:54
No problem! I'm using pyright in python (and also null-ls plugin).

**Comment by WhoIsSethDaniel** [comment] 2023-01-24 20:19
I don't have the dart lsp server to work with but my assumption would be that the dart lsp server isn't sending back a 'done' message. Or somehow the messages are out of order.  @rorystephenson do you have an example of a typical set of messages from the dart lsp server?

**Comment by strdr4605** [comment] 2023-01-30 13:32
I also have this issue when the server will stay In Progress forever

```
 [null-ls] 🌒  Initializing…: (In Progress) [copilot] 🌒  Initializing…: (In Progress)       
```

:LspInfo
```
 3 client(s) attached to this buffer: 
 
 Client: null-ls (id: 1, bufnr: [1])
 	filetypes:       sh, css, vue, handlebars, typescriptreact, less, yaml, graphql, jsonc, json, typescript, markdown, html, scss, markdown.mdx, javascript, javascriptreact, lua, luau
 	autostart:       false
 	root directory:  /Users/strdr4605/.dotfiles
 	cmd:             <function>
 
 Client: sumneko_lua (id: 2, bufnr: [1])
 	filetypes:       lua
 	autostart:       true
 	root directory:  /Users/strdr4605/.dotfiles/nvim
 	cmd:             lua-language-server
 
 Client: copilot (id: 3, bufnr: [1])
 	filetypes:       
 	autostart:       false
 	root directory:  /Users/strdr4605/.dotfiles
 	cmd:             node /Users/strdr4605/.local/share/nvim/site/pack/packer/opt/copilot.lua/copilot/index.js
```

**Comment by WhoIsSethDaniel** [comment] 2023-01-31 20:32
@strdr4605 is this all servers or just some servers?  Which servers?

**Comment by strdr4605** [comment] 2023-01-31 20:53
It looks like; I am not advanced in this. How can I test that it affects all servers

https://user-images.githubusercontent.com/16056918/215880167-b37867f0-836f-4ad0-aed2-ad4adf5b9285.mov

**Comment by WhoIsSethDaniel** [comment] 2023-01-31 21:18
@strdr4605 sorry I was unclear. I mean do all servers *that you use* exhibit this issue? Your video seems to say "yes, all servers I use exhibit this issue."

**Comment by rlees85** [comment] 2023-02-06 14:18
I am having this issue on all language servers (terraform/powershell/bicep/yaml/bash/dockerfile/etc...)... thanks for the plugin by the way!

**Comment by WhoIsSethDaniel** [comment] 2023-02-07 20:05
I am able to replicate this. I will have a look.

**Comment by WhoIsSethDaniel** [comment] 2023-02-07 20:14
If I comment out the autocmd for `LspAttach` this problem goes away. Still trying to see why.

**Comment by WhoIsSethDaniel** [comment] 2023-02-07 20:51
I believe the issue is resolved in the most recent `master`. Please LMK.

**Comment by petobens** [comment] 2023-02-08 01:33
Hi @WhoIsSethDaniel ! I think that this is mostly fixed however for pyright (python lsp) I'm always seeing the commenced icon/message.. Can that be fixed?

![image](https://user-images.githubusercontent.com/2583971/217405781-0b1e51fb-1ff6-4427-806d-7b809569ad01.png)

**Comment by WhoIsSethDaniel** [comment] 2023-02-08 17:25
@petobens It's hard to say. I'm not familiar with pyright (or python) so it may be difficult to test. I don't see this issue and have had no luck replicating it. I may need some assistance from you to help resolve the issue.

**Comment by WhoIsSethDaniel** [comment] 2023-02-08 22:59
It seems the reason is that `pyright` doesn't send status messages. The PR that triggered this (#4) doesn't account for this scenario and simply stuffs an "Initializing" message into the message queue. I may have to make the changes in #4 (as well as changes I made in #7) optional and based on server name. I don't entirely understand the problem #4 was trying to solve and I am assuming that it solves some problem in at least a small number of LSP servers.

**Comment by petobens** [comment] 2023-02-08 23:02
Great that you managed to track it down! Thanks

**Comment by WhoIsSethDaniel** [comment] 2023-02-08 23:05
I've re-read #4 and it simply allows for a status update more quickly than what was being observed. This seems useful for LSP servers that take a long time to send their first status message.  I'll need to think about how to deal with this in config.

**Comment by WhoIsSethDaniel** [comment] 2023-02-08 23:08
The plugin may also be able to retrieve server capabilities and see if the server claims to send status messages. That may be the best solution assuming it is reliable.

**Comment by WhoIsSethDaniel** [comment] 2023-02-08 23:16
It doesn't look like the sever capabilities announce that status messages will be forthcoming. If anyone knows any different please let me know.

**Comment by WhoIsSethDaniel** [comment] 2023-02-10 02:59
@petobens you can now `hide` a server from ever showing status. e.g.
```
{ `lsp_progress', hide = { 'pyright' } }
```

**Comment by petobens** [comment] 2023-02-12 10:59
Thank! I believe this issue is now resolved. Feel free to close

**Closed** 2023-02-12 17:42 UTC
